### ISSUE TITLE
LAS Picks Storage

### ISSUE THREAD

**Issue by wetux** [MichaelTunnell/las-picks#24]
Why do you use data.php file for arrays if you can use a better way. Store everything into seperate files by year in YAML. Much clearner.

Example Directory:
```
/data/las-2015.yaml
/data/las-2014.yaml
...
/data/las-2007.yaml
/data/las-2006.yaml
```

Example YAML Stracture:
```YAML
#
# Linux Action Show 2015 Picks
# Last Updated: 2015-05-17
#

LAS-365:
  date: 2015-05-17
  title: The Emulation Game
  post: http://www.jupiterbroadcasting.com/82207/the-emulation-game-las-365/
  picks:
    - runslinux:
      name: Meet The Smart Fridge That Runs Ubuntu
      site: http://www.omgubuntu.co.uk/2015/05/meet-the-smart-fridge-that-runs-ubuntu
    - desktopapp:
      name: Wireshark 1.12.5
      site: https://www.wireshark.org/docs/relnotes/wireshark-1.12.5.html
    - spotlight:
      name: Multi-Platform BitTorrent Client qBittorrent Sees New Major Release
      site: http://www.webupd8.org/2015/05/multi-platform-bittorrent-client.html
    - android:
      source: ting
      name: Some Android Software Here
      site: Android App URL Here

#EOF: ./data/las-2015.yaml
```

Example Code to loop throught all files:
```php
foreach (range(2006, 2015) as $year) {
  $file = "data/las-{$year}.yaml";
  if (file_exists($file)) {
    $data = yaml_file_parse($file);
  } #file/check
} #each/year
```

Then you can use php ``yaml_parse_file`` to convert it to array. Just make sure you use "spaces" and not "tabs" when you edit YAML files. For older episodes you can use ``LAS-001`` for example.
